// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export const options = {
  stages: [
    { duration: '1m', target: 10 }, // traffic ramp-up from 1 to 10 users over a minute.
    { duration: '5m', target: 30 }, // stay at 30 users for 5 minutes
    { duration: '1m', target: 0 }, // ramp-down to 0 users
  ],
  tags: {
    name: 'demo-api-go',
    type: 'load-test',
    testid: 'demo-api-go',
    scenario: 'login and get user',
  },
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function () {
  postman[Request]({
    name: "Login",
    id: "40c3ee34-bd06-4444-a666-ca727910fd81",
    method: "POST",
    headers: {
      'Content-Type': 'application/json',
    },
    address: "http://api:8080/login",
    data: JSON.stringify({ user: "user", pass: "pass" }),
    post(response) {
      pm.test("Status code is 200", function () {
        pm.response.to.have.status(200);
      });
    }
  });

  postman[Request]({
    name: "Get user",
    id: "4a500f3e-3856-40c3-948a-25ea9586be29",
    method: "GET",
    
    address: "http://api:8080/users/4",
    post(response) {
      pm.test("Status code is 200", function () {
        pm.response.to.have.status(200);
      });
    }
  });
}
